# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.1
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    git \
    curl \
    libyaml-dev && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

COPY Gemfile ./
RUN bundle install

EXPOSE 3000
